In [ ]:
# 1-1. 문법이 간결해 빠르게 코드로 옮길 수 있다
data= [1,2,3,4]

doubled = [x * 2 for x in data]

print(doubled)

[2, 4, 6, 8]


In [ ]:
# 2-3. NumPy 설치

!pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.2.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
# 3-1. 배열 만들기

import numpy as np

a = np.array([1, 2, 3, 4, 5])
print(a)       # [1 2 3 4 5]
print(type(a)) # <class 'numpy.ndarray'>


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:

# 3-2. 1차원 / 2차원 / 3차원 배열

# 1차원 — 벡터 (데이터 한 줄)
a1 = np.array([1, 2, 3])

# 2차원 — 행렬 (표 형태, 이미지 1장)
a2 = np.array([[1, 2, 3],
               [4, 5, 6]])

# 3차원 — 여러 행렬의 묶음 (컬러 이미지, 여러 장의 이미지)
a3 = np.array([[[1, 2], [3, 4]],
               [[5, 6], [7, 8]]])

print(a1)
print(a2)
print(a3)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# 3-3. 배열의 형태 확인
a2 = np.array([[1, 2, 3],
               [4, 5, 6]])

print(a2.shape)  # (2, 3) → 2행 3열
print(a2.ndim)   # 2 → 2차원
print(a2.dtype)  # int64 → 정수형

(2, 3)
2
int64


In [6]:
# 4-1. 배열 생성 함수

np.zeros((3, 3))       # 0으로 채운 3×3 배열
np.ones((2, 4))        # 1로 채운 2×4 배열
np.arange(0, 10, 2)    # [0 2 4 6 8] — 범위로 생성
np.linspace(0, 1, 5)   # [0. 0.25 0.5 0.75 1.] — 균등 간격
np.random.rand(3, 3)   # 0~1 사이 난수 3×3 배열


array([[0.48928705, 0.59739501, 0.11179506],
       [0.235751  , 0.56875898, 0.25033015],
       [0.3500502 , 0.22118192, 0.16039295]])

In [8]:
# 4-2. 배열 연산 — 브로드캐스팅

a = np.array([1, 2, 3, 4])

print(a + 10)    # [11 12 13 14]
print(a * 2)     # [ 2  4  6  8]
print(a ** 2)    # [ 1  4  9 16]

b = np.array([10, 20, 30, 40])
print(a + b)     # [11 22 33 44]



[11 12 13 14]
[2 4 6 8]
[ 1  4  9 16]
[11 22 33 44]


In [9]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
print(a + 100)
# [[101 102 103]
#  [104 105 106]]


[[101 102 103]
 [104 105 106]]


In [10]:
# 4-3. 인덱싱 & 슬라이싱

a = np.array([10, 20, 30, 40, 50])

print(a[0])      # 10 — 첫 번째 요소
print(a[-1])     # 50 — 마지막 요소
print(a[1:4])    # [20 30 40] — 슬라이싱

b = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print(b[1, 2])   # 6 — 1행 2열
print(b[:, 1])   # [2 5 8] — 전체 행의 1열
print(b[0:2, :]) # 0~1행 전체

10
50
[20 30 40]
6
[2 5 8]
[[1 2 3]
 [4 5 6]]


In [11]:
a = np.array([1, 2, 3, 4, 5])

print(np.sum(a))   # 15
print(np.mean(a))  # 3.0
print(np.max(a))   # 5
print(np.min(a))   # 1
print(np.std(a))   # 표준편차: 1.414...

15
3.0
5
1
1.4142135623730951


In [12]:
# 5-1. 이미지 데이터를 숫자 배열로 표현하는 법

# 28×28 흑백 이미지 (MNIST 손글씨 숫자 데이터셋)
image = np.random.randint(0, 256, size=(28, 28))
print(image.shape)  # (28, 28)

# 컬러 이미지 (RGB)
color_image = np.random.randint(0, 256, size=(64, 64, 3))
print(color_image.shape)  # (64, 64, 3)

(28, 28)
(64, 64, 3)
